[package]
name = "farcaster_core"
description = "Farcaster project core library."
version = "0.1.0"
authors = ["Farcaster Devs"]
license = "LGPL-3.0"
homepage = "https://github.com/farcaster-project/farcaster-core"
repository = "https://github.com/farcaster-project/farcaster-core"
documentation = "https://docs.rs/farcaster_core"
readme = "README.md"
include = [
    "src/*",
    "README.md",
    "LICENSE",
]

edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rpc = []
serde = ["serde_crate", "bitcoin/use-serde", "monero/serde_support"]

[dependencies]
amplify = "3.7.1"
hex = "0.4.3"
tiny-keccak = { version = "2", features = ["keccak"] }
fixed-hash = { version = "0.7.0", default-features = false }
strict_encoding = "=1.2.3"
strict_encoding_derive = "=1.5.2"
lightning_encoding = "0.4.0-beta.1"
thiserror = "1.0.24"
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
internet2 = { git = "https://github.com/zkao/rust-internet2", branch = "farcaster" }

# blockchain specific
bitcoin = "0.26"
monero = { version = "0.13" }

[dev-dependencies]
bitcoincore-rpc = "0.13.0"
rand_core = { version = "^0.6.3", features = ["getrandom"] }
secp256k1 = { version = "0.20.1", features = ["rand-std"] }
internet2 = { git = "https://github.com/zkao/rust-internet2", branch = "farcaster" }
lazy_static = "1.4.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
